# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180331_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='permanent_url',
            field=models.CharField(help_text='Debe ser único sin espacios ni caracteres especiales', max_length=255, unique=True, verbose_name='Url del post(/blog/slug)'),
            preserve_default=False,
        ),
    ]
